version: '3.8'

services: 
 db: 
  image: mysql:8
  container_name: cs50-final-project
  restart: always
  environment: 
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: reservation_management   
  ports:
  - "3306:3306"
  volumes:
  - ./data:/var/lib/mysql