services: 
  springboot-app:
    image: thaolo/bookwise-app:latest      
    ports: 
      - "8080:8080"
    volumes:
      - /home/ubuntu/myapp/config:/app/config
    command: >
      java -jar bookwise-docker.jar
      --spring.config.location=file:/app/config/
      --spring.profiles.active=prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_DATABASE: 0
      SPRING_REDIS_SSL: true
      AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT: true    
    depends_on:
      redis:
        condition: service_healthy      
        
    #restart: always

  redis: 
   image: redis:7   
   ports: 
     - "6379:6379" 
   healthcheck:
     test: ["CMD", "redis-cli", "ping"]
     interval: 10s
     timeout: 5s
     retries: 5
