services: 
  springboot-app:
    image: thaolo/bookwise-app:latest      
    ports: 
      - "8080:8080"
    volumes:
      - /home/ubuntu/myapp/config:/app/config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: >-
        -Dspring.config.additional-location=file:/app/config/
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  redis: 
   image: redis:7   
   ports: 
     - "6379:6379" 
   healthcheck:
     test: ["CMD", "redis-cli", "ping"]
     interval: 10s
     timeout: 5s
     retries: 5
